// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: comments.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createComment = `-- name: CreateComment :one
INSERT INTO
    comments (
        dilemma_id,
        user_id,
        content,
        parent_id
    )
VALUES ($1, $2, $3, $4)
RETURNING
    id, dilemma_id, user_id, content, parent_id, created_at
`

type CreateCommentParams struct {
	DilemmaID pgtype.UUID `json:"dilemma_id"`
	UserID    pgtype.UUID `json:"user_id"`
	Content   string      `json:"content"`
	ParentID  pgtype.UUID `json:"parent_id"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment,
		arg.DilemmaID,
		arg.UserID,
		arg.Content,
		arg.ParentID,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.DilemmaID,
		&i.UserID,
		&i.Content,
		&i.ParentID,
		&i.CreatedAt,
	)
	return i, err
}

const listCommentsByDilemma = `-- name: ListCommentsByDilemma :many
SELECT c.id, c.dilemma_id, c.user_id, u.username, c.content, c.parent_id, c.created_at
FROM comments c
    JOIN users u ON u.id = c.user_id
WHERE
    c.dilemma_id = $1
ORDER BY c.created_at DESC
LIMIT $2
OFFSET
    $3
`

type ListCommentsByDilemmaParams struct {
	DilemmaID pgtype.UUID `json:"dilemma_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

type ListCommentsByDilemmaRow struct {
	ID        pgtype.UUID        `json:"id"`
	DilemmaID pgtype.UUID        `json:"dilemma_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Username  string             `json:"username"`
	Content   string             `json:"content"`
	ParentID  pgtype.UUID        `json:"parent_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListCommentsByDilemma(ctx context.Context, arg ListCommentsByDilemmaParams) ([]ListCommentsByDilemmaRow, error) {
	rows, err := q.db.Query(ctx, listCommentsByDilemma, arg.DilemmaID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommentsByDilemmaRow
	for rows.Next() {
		var i ListCommentsByDilemmaRow
		if err := rows.Scan(
			&i.ID,
			&i.DilemmaID,
			&i.UserID,
			&i.Username,
			&i.Content,
			&i.ParentID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
