// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Comment struct {
	ID        pgtype.UUID        `json:"id"`
	DilemmaID pgtype.UUID        `json:"dilemma_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Content   string             `json:"content"`
	ParentID  pgtype.UUID        `json:"parent_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Dilemma struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Title       string             `json:"title"`
	IsAnonymous bool               `json:"is_anonymous"`
	Status      string             `json:"status"`
	TotalVotes  int32              `json:"total_votes"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type DilemmaOption struct {
	ID        pgtype.UUID `json:"id"`
	DilemmaID pgtype.UUID `json:"dilemma_id"`
	Label     string      `json:"label"`
	VoteCount int32       `json:"vote_count"`
}

type Report struct {
	ID         pgtype.UUID        `json:"id"`
	ReporterID pgtype.UUID        `json:"reporter_id"`
	DilemmaID  pgtype.UUID        `json:"dilemma_id"`
	CommentID  pgtype.UUID        `json:"comment_id"`
	Reason     string             `json:"reason"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID        pgtype.UUID        `json:"id"`
	Username  string             `json:"username"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Vote struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	DilemmaID pgtype.UUID        `json:"dilemma_id"`
	OptionID  pgtype.UUID        `json:"option_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
