// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reports.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCommentReport = `-- name: CreateCommentReport :one
INSERT INTO
    reports (
        reporter_id,
        comment_id,
        reason
    )
VALUES ($1, $2, $3)
RETURNING
    id, reporter_id, dilemma_id, comment_id, reason, created_at
`

type CreateCommentReportParams struct {
	ReporterID pgtype.UUID `json:"reporter_id"`
	CommentID  pgtype.UUID `json:"comment_id"`
	Reason     string      `json:"reason"`
}

func (q *Queries) CreateCommentReport(ctx context.Context, arg CreateCommentReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, createCommentReport, arg.ReporterID, arg.CommentID, arg.Reason)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ReporterID,
		&i.DilemmaID,
		&i.CommentID,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const createDilemmaReport = `-- name: CreateDilemmaReport :one
INSERT INTO
    reports (
        reporter_id,
        dilemma_id,
        reason
    )
VALUES ($1, $2, $3)
RETURNING
    id, reporter_id, dilemma_id, comment_id, reason, created_at
`

type CreateDilemmaReportParams struct {
	ReporterID pgtype.UUID `json:"reporter_id"`
	DilemmaID  pgtype.UUID `json:"dilemma_id"`
	Reason     string      `json:"reason"`
}

func (q *Queries) CreateDilemmaReport(ctx context.Context, arg CreateDilemmaReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, createDilemmaReport, arg.ReporterID, arg.DilemmaID, arg.Reason)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ReporterID,
		&i.DilemmaID,
		&i.CommentID,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}
